apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: env-app
  template:
    metadata:
      labels:
        app: env-app
    spec:
      containers:
      - name: app-container
        image: introbondocker/local-env
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: env-service
spec:
  type: NodePort
  selector:
    app: env-app
  ports:
    - port: 1234
      targetPort: 1234
      nodePort: 31234
