version: "3.7"
services:
  app:
    build: .
    init: true
    container_name: env_con
    hostname: env
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 1234:1234
