services:
  # application management
  heimdall:
    image: ${HEIMDALL_IMAGE:-lscr.io/linuxserver/heimdall:latest}
    container_name: heimdall-con
    hostname: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 8180:80
    volumes:
      - ../data/heimdall/config:/config
  dashy:
    image: ${DASHY_IMAGE:-lissy93/dashy:latest}
    hostname: dashy
    container_name: dashy-con
    ports:
      - 8181:80
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s