services:
  portainer:
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    init: true
    container_name: portainer-con
    hostname: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - ../data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  yacht:
    image: ${YACTH_IMAGE:-selfhostedpro/yacht:latest}
    init: true
    container_name: yacht-con
    hostname: yacht
    restart: always
    ports:
      - "9444:8000"
    volumes:
      - ../data/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock

  rancher:
    image: rancher/rancher
    privileged: true
    restart: unless-stopped
    ports:
      - "20080:80"
      - "20443:443"