services:
  ctfreak:
    image: jypsoftware/ctfreak
    container_name: ctfreak
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "6700:6700"
    volumes:
      - ./ctfreak-data:/data
    restart: "unless-stopped"