services:
  redis:
    image: ${REDIS_IMAGE:-redis:7.0.8-alpine}
    init: true
    container_name: redis-con
    hostname: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    init: true
    container_name: redisinsight-con
    ports:
      - "8004:8001"
    environment:
      - TZ=UTC
    volumes:
      - redisinsight-data:/db
    restart: always

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: rabbitmq-con
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always