services:
  postgres:
      image: ${POSTGRES_IMAGE:-postgres:13-alpine3.17}
      init: true
      container_name: postgres-con
      hostname: postgres
      restart: always
      ports:
          - 5432:5432
      environment:
          - POSTGRES_USER=jb
          - POSTGRES_PASSWORD=12345678
          - POSTGRES_DB=init