services:
  redisinsight:
    image: redislabs/redisinsight:latest
    init: true
    container_name: redisinsight-con
    ports:
      - "8004:8001"
    environment:
      - TZ=UTC
    volumes:
      - redisinsight-data:/db
    restart: always

