services:

  uptime-kuma:
      image: ${UPTIME_KUMA_IMAGE:-louislam/uptime-kuma:1}
      container_name: uptime-kuma-con
      hostname: uptime-kuma
      volumes:
          - ../data/uptime-kuma-data:/app/data
      ports:
          - 18001:3001
      restart: always
