services:
  ctfreak:
    image: jypsoftware/ctfreak
    container_name: ctfreak
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "6700:6700"
    volumes:
      - ./ctfreak-data:/data
    restart: "unless-stopped"

  crontab-ui:
    image: alseambusher/crontab-ui:latest
    container_name: crontab-ui
    restart: always
    ports:
      - "18000:8000"
    volumes:
      - ../data/crontabs:/crontab-ui/crontabs

  uptime-kuma:
    image: ${UPTIME_KUMA_IMAGE:-louislam/uptime-kuma:1}
    container_name: uptime-kuma-con
    hostname: uptime-kuma
    volumes:
      - ../data/uptime-kuma-data:/app/data
    ports:
      - "18001:3001"
    restart: always