services:
  ctfreak:
    image: jypsoftware/ctfreak
    container_name: ctfreak-con
    hostname: ctfreak
    restart: always
    volumes:
      - ../data/ctfreak-data:/data
    ports:
      - "6700:6700"
    environment:
      - TZ=Asia/Bangkok

  crontab-ui:
    image: alseambusher/crontab-ui:latest
    container_name: crontab-ui-con
    hostname: crontab-ui
    restart: always
    volumes:
      - ../data/crontabs:/crontab-ui/crontabs
    ports:
      - "18000:8000"

  uptime-kuma:
    image: ${UPTIME_KUMA_IMAGE:-louislam/uptime-kuma:1}
    container_name: uptime-kuma-con
    hostname: uptime-kuma
    volumes:
      - ../data/uptime-kuma-data:/app/data
    ports:
      - "18001:3001"
    restart: always