version: '3.9'

services:
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    command: ngrok http ${NGROK_PORT:-80} --authtoken=${NGROK_AUTHTOKEN:-your_default_ngrok_authtoken} --region=us --log=stdout
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN:-your_default_ngrok_authtoken}
