FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY data.json .

ENV PORT=3000
ENV DATA_FILE=/app/data.json
ENV TZ=<your-timezone>

EXPOSE 3000

CMD [ "npm", "start" ]
