version: "3"

services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - DATA_FILE=/app/data.json   # Add this line to set an environment variable for the data file path
    volumes:
      - ./data.json:/app/data.json  # Add this line to mount the local file as a volume in the container
