version: "3.1"
services:
  mongo:
    image: mongo:latest
    init: true
    container_name: mongo-con
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "${PORT:-27017}:27017"
