0 PACKAGES PILOT: packages_menu
1 ZSH with essential plugins: zsh
2 Docker engine with docker compose v2: docker
3 Python version manager(pyenv): pyenv
4 NodeJS version manager(nvm): nvm
5 Go version manager (gvm): gvm
99 Exit: exit
