version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "30030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    networks:
      - backend

networks:
    backend:
        driver: bridge
