version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole-con
    hostname: pihole
    image: ${PIHOLE_IMAGE}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Bangkok'
      WEBPASSWORD: 1234
    volumes:
      - './data/etc-pihole:/etc/pihole'
      - './data/etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped


  # nginx:
  #   image: ${NGINX_IMAGE}
  #   container_name: nginx_con
  #   hostname: nginx
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - ./data:/nginx/config
  #   ports:
  #     - 82:80
  #     - 444:443

  npm:
    image: ${NPM_IMAGE}
    container_name: proxy-manager-con
    hostname: proxy-manager
    restart: unless-stopped
    ports:
      - 180:80
      - 181:81
      - 1443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  wireshark:
    image: ${WIRESHARK_IMAGE}
    container_name: wireshark-con
    hostname: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 23000:3000 
      - 23001:3001
    restart: unless-stopped

volumes:
  data: