version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: ${PIHOLE_IMAGE}
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
      - "10067:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "10080:80/tcp"
    environment:
      TZ: 'Asia/Bangkok'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './data/etc-pihole:/etc/pihole'
      - './data/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped