0 SYSTEM MENU: SYSTEM_MENU
1 Update system: update
2 Cleanup system: cleanup
3 Check network status & test speed: check_network_status
4 Check installed packages: check_installed_packages
99 Back to main menu: exit
