services:
  influx:
    image: ${INFLUX_IMAGE:-influxdb:latest}
    init: true
    container_name: influx-con
    hostname: influx
    restart: always
    ports:
      - "8086:8086"

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:13-alpine3.17}
    init: true
    container_name: postgres-con
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jb
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=init

  pgadmin:
    image: ${PGADMIN_IMAGE:-dpage/pgadmin4:latest}
    init: true
    container_name: pgadmin-con
    hostname: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@swd.dev}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-swd12345}
    ports:
      - ${PGADMIN_PORT:-5050}:80

  mongo:
    image: mongo:latest
    init: true
    container_name: mongo-con
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "${PORT:-27017}:27017"

  mysql:
    image: mysql:latest
    init: true
    container_name: mysql-con
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: init
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    init: true
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
