services:
  # kafka stack
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # kafka stack
  kafka:
    image: "wurstmeister/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # network
  pihole:
    image: ${PIHOLE_IMAGE:-pihole/pihole:latest}
    container_name: pihole-con
    hostname: pihole
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "1067:67/udp"
      - "1080:80/tcp"
      - "1443:443/tcp"
    environment:
      TZ: "Asia/Bangkok"
      WEBPASSWORD: 1234
    volumes:
      - "../data/etc-pihole:/etc/pihole"
      - "../data/etc-dnsmasq.d:/etc/dnsmasq.d"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always
